version: "3"
services: 

    go-echo: 
        build: 
            context: ./environments/go-echo
        volumes:
        - ./go-echo/src:/go/src
        ports: 
            - 3000:3000
        tty: true

    react:
        build: 
            context: ./environments/react
        volumes:
            - ./react/app:/usr/src/app
        tty: true
        working_dir: /usr/src/app
        # command: sh -c "cd react-sample && yarn start"
        command: sh -c "cd dependency && npm start"
        ports:
            - "8080:3000"
            - "5001:5000"
    
    # nginx:
    #     build: 
    #         context: ./environments/nginx
    #     container_name: nginx
    #     ports:
    #         - "1234:1234"
    #     volumes:
    #         - ./environments/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        
    # elasticsearch:
    #     build:
    #         context: ./elasticsearch
    #         dockerfile: dockerfile
    #     container_name: elasticsearch-sudachi
    #     volumes:
    #         - ./elasticsearch/node_data:/usr/share/elasticsearch/data
    #     environment:
    #         - discovery.type=single-node
    #         - cluster.name=docker-cluster
    #         - bootstrap.memory_lock=true
    #         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
    #     ports:
    #         - 9200:9200
    #     tty: true
        

